### ISSUE TITLE
"租户" 没有值，如何注册？

### ISSUE THREAD

**Issue by zengxinle** [neozhu/smartadmin.core.urf#2]
"租户" 没有值，如何注册用户 ？

不种点 “用户”，不知道如何进入系统。好在我能直接操作数据库。

**Comment by neozhu** [comment]
是注册新用户的时候吗

**Comment by zengxinle** [comment]
是注册新用户，需要 “租户”，但又没有增加：“租户“ 的链接页面。

**提示：**   我是下了整个源代码在本地运行。

**Comment by zengxinle** [comment]
当然，感谢你还提供了一个原装的 SmartAdmin - ASP.NET Core Responsive WebApp 的包。

本来以为是  HTML 版本，发现是 ASP.NET Core 的专用版本。 一直想试试。

**Comment by zengxinle** [comment]
![image](https://user-images.githubusercontent.com/2024190/95475077-72d31280-09b8-11eb-8d6b-01ffb95ec4d2.png)

**Comment by neozhu** [comment]
/Tenants/Index
![微信截图_20201009184625](https://user-images.githubusercontent.com/1549611/95574589-c3ea1180-0a5f-11eb-96e1-50ec7296eb22.png)
这里维护好，注册的时候就是从这里取的值
