### ISSUE TITLE
建议把数据库脚本放出来不要mdf

### ISSUE THREAD

**Issue by jhzou1** [neozhu/smartadmin.core.urf#4]
建议把完整的数据库脚本放出来不要mdf,mdf里面数据版本为904即MSSQL2019,如果比较低的版本无法附加。

**Comment by neozhu** [comment]
你可以安装最新的LocalDb，非常方便。

**Comment by jhzou1** [comment]
很不错，期待能有Mysql的支持

**Comment by neozhu** [comment]
mysql 原生支持的,换一下连接字符串就可以了，因为用的就是entityframework core。
