### ISSUE TITLE
改善建议权限授权

### ISSUE THREAD

**Issue by jhzou1** [neozhu/smartadmin.core.urf#5]
这个框架看起来确实采用了不少新的东西包括Ioc,没事美中不足的地方还是有点点的，所以建议一下

1.角色授权这里扩展功能的权限授权应该是树形的，这样更容易扩展，比如某个菜单独有的功能，如果按列加我们还需要写固定加一个功能，如果一个界面有很多功能按钮都需要管控授权，明显这个不行的，当然不知道你这里改的话是不是要有很大的改动逻辑
Yisha框架的那个角色权限菜单树是不错的，如果是那种更好

2.这个页面每次只能打开一个菜单编辑界面，要是能在上面做成tab这样更好，比如窗口1，窗口2，这些能集成在框架里面这个框架还是非常不错的

**Comment by neozhu** [comment]
谢谢你的建议，有时间我会改进的，现在的授权也就是到页面级,并没有实现按钮级的授权可配置，当然最主要的是我现在接的项目都是小项目，业务也不复杂，但速度要快，1-2周必须做出原型让客户确认的那种。重点还是在业务本身。
关于第二点，我就很不喜欢那种一个一个tab打开，如果还是iframe实现的话真的体验非常的差，开多了影响性能，容易假死，相互传参也很麻烦。
